version: "3.9"

services:
  backend:
    tty: true
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.backend
      args:
        # [Choice] Python version: 3, 3.8, 3.7, 3.6
        IMAGE: python:3.11

    volumes:
      - ..:/workspace:cached

    env_file:
      - ../.env
    command: sh -c "cd /workspace/backend && alembic upgrade head && uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000

  frontend:
    tty: true
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.frontend
    volumes:
      - ..:/workspace:cached

    env_file:
      - ../.env
    command: sh -c "cd /workspace/frontend && yarn run dev --host"
    ports:
      - 4321:4321
  

  
    # network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: hostPrice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    expose:
      - 5432

  pgadmin:
      container_name: PGADMIN
      image: dpage/pgadmin4:latest
      restart: unless-stopped
      env_file:
        -  ../.env


      volumes:
        - pgadmin:/var/lib/pgadmin
      ports:
        - 80:80
      depends_on:
        - db


volumes:
  postgres-data:
  pgadmin:

